import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:poker_dice/services/storage_service.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'storage_service_test.mocks.dart';

/// Mock implementation of SharedPreferences for testing.
///
/// Generated by mockito to stub SharedPreferences methods.
@GenerateMocks([SharedPreferences])
/// Tests for [HighScore] model and [StorageService].
///
/// Covers serialization, persistence, sorting, and error handling.
void main() {
  group('HighScore', () {
    test('creates with required parameters', () {
      final DateTime now = DateTime(2024, 1, 1, 12, 0, 0);
      final HighScore score = HighScore(score: 100, timestamp: now);
      expect(score.score, equals(100));
      expect(score.timestamp, equals(now));
    });

    test('serializes to JSON map correctly', () {
      final DateTime now = DateTime(2024, 1, 1, 12, 0, 0);
      final HighScore score = HighScore(score: 150, timestamp: now);
      final Map<String, dynamic> json = score.toJson();
      expect(json['score'], equals(150));
      expect(json['timestamp'], equals(now.toIso8601String()));
    });

    test('deserializes from JSON map correctly', () {
      final Map<String, dynamic> json = {
        'score': 200,
        'timestamp': '2024-06-15T10:30:00.000000',
      };
      final HighScore score = HighScore.fromJson(json);
      expect(score.score, equals(200));
      expect(score.timestamp, equals(DateTime.parse('2024-06-15T10:30:00.000000')));
    });

    test('serializes to JSON string correctly', () {
      final DateTime now = DateTime(2024, 1, 1, 12, 0, 0);
      final HighScore score = HighScore(score: 75, timestamp: now);
      final String jsonString = score.toJsonString();
      expect(jsonString, isA<String>());
      expect(jsonString, contains('"score":75'));
    });

    test('deserializes from JSON string correctly', () {
      final String jsonString =
          '{"score":300,"timestamp":"2024-03-20T15:45:00.000000"}';
      final HighScore score = HighScore.fromJsonString(jsonString);
      expect(score.score, equals(300));
      expect(score.timestamp, equals(DateTime.parse('2024-03-20T15:45:00.000000')));
    });

    test('equality operator works correctly', () {
      final DateTime now = DateTime(2024, 1, 1);
      final HighScore a = HighScore(score: 100, timestamp: now);
      final HighScore b = HighScore(score: 100, timestamp: now);
      final HighScore c = HighScore(score: 200, timestamp: now);
      expect(a == b, isTrue);
      expect(a == c, isFalse);
    });

    test('hashCode is consistent with equality', () {
      final DateTime now = DateTime(2024, 1, 1);
      final HighScore a = HighScore(score: 100, timestamp: now);
      final HighScore b = HighScore(score: 100, timestamp: now);
      expect(a.hashCode, equals(b.hashCode));
    });

    test('toString returns meaningful representation', () {
      final DateTime now = DateTime(2024, 1, 1);
      final HighScore score = HighScore(score: 100, timestamp: now);
      expect(score.toString(), contains('HighScore'));
      expect(score.toString(), contains('100'));
    });
  });

  group('StorageService', () {
    late MockSharedPreferences mockPrefs;
    late StorageService service;

    setUp(() {
      mockPrefs = MockSharedPreferences();
      service = StorageService(prefs: mockPrefs);
    });

    group('saveHighScore', () {
      test('saves new score to empty storage', () async {
        when(mockPrefs.getStringList(StorageService.HIGH_SCORES_KEY))
            .thenReturn(null);
        when(mockPrefs.setStringList(any, any)).thenAnswer((_) async => true);

        final bool result = await service.saveHighScore(100);

        expect(result, isTrue);
        verify(mockPrefs.setStringList(
          StorageService.HIGH_SCORES_KEY,
          any,
        )).called(1);
      });

      test('adds score to existing scores', () async {
        final String existingScore = HighScore(
          score: 200,
          timestamp: DateTime(2024, 1, 1),
        ).toJsonString();
        when(mockPrefs.getStringList(StorageService.HIGH_SCORES_KEY))
            .thenReturn([existingScore]);
        when(mockPrefs.setStringList(any, any)).thenAnswer((_) async => true);

        final bool result = await service.saveHighScore(150);

        expect(result, isTrue);
        verify(mockPrefs.setStringList(
          StorageService.HIGH_SCORES_KEY,
          any,
        )).called(1);
      });

      test('returns false on save failure', () async {
        when(mockPrefs.getStringList(StorageService.HIGH_SCORES_KEY))
            .thenReturn(null);
        when(mockPrefs.setStringList(any, any)).thenAnswer((_) async => false);

        final bool result = await service.saveHighScore(100);

        expect(result, isFalse);
      });

      test('returns false on exception', () async {
        when(mockPrefs.getStringList(StorageService.HIGH_SCORES_KEY))
            .thenThrow(Exception('Storage error'));

        final bool result = await service.saveHighScore(100);

        expect(result, isFalse);
      });
    });

    group('getHighScores', () {
      test('returns empty list when no scores stored', () async {
        when(mockPrefs.getStringList(StorageService.HIGH_SCORES_KEY))
            .thenReturn(null);

        final List<HighScore> scores = await service.getHighScores();

        expect(scores, isEmpty);
      });

      test('returns empty list when storage is empty', () async {
        when(mockPrefs.getStringList(StorageService.HIGH_SCORES_KEY))
            .thenReturn([]);

        final List<HighScore> scores = await service.getHighScores();

        expect(scores, isEmpty);
      });

      test('returns scores in descending order', () async {
        final List<String> scoreStrings = [
          HighScore(score: 100, timestamp: DateTime(2024, 1, 1)).toJsonString(),
          HighScore(score: 300, timestamp: DateTime(2024, 1, 2)).toJsonString(),
          HighScore(score: 200, timestamp: DateTime(2024, 1, 3)).toJsonString(),
        ];
        when(mockPrefs.getStringList(StorageService.HIGH_SCORES_KEY))
            .thenReturn(scoreStrings);

        final List<HighScore> scores = await service.getHighScores();

        expect(scores.length, equals(3));
        expect(scores[0].score, equals(300));
        expect(scores[1].score, equals(200));
        expect(scores[2].score, equals(100));
      });

      test('skips invalid entries and returns valid scores', () async {
        final List<String> scoreStrings = [
          HighScore(score: 100, timestamp: DateTime(2024, 1, 1)).toJsonString(),
          'invalid_json',
          HighScore(score: 200, timestamp: DateTime(2024, 1, 2)).toJsonString(),
        ];
        when(mockPrefs.getStringList(StorageService.HIGH_SCORES_KEY))
            .thenReturn(scoreStrings);

        final List<HighScore> scores = await service.getHighScores();

        expect(scores.length, equals(2));
        expect(scores[0].score, equals(200));
        expect(scores[1].score, equals(100));
      });

      test('returns empty list on exception', () async {
        when(mockPrefs.getStringList(StorageService.HIGH_SCORES_KEY))
            .thenThrow(Exception('Storage error'));

        final List<HighScore> scores = await service.getHighScores();

        expect(scores, isEmpty);
      });
    });

    group('clearHighScores', () {
      test('clears high scores successfully', () async {
        when(mockPrefs.remove(StorageService.HIGH_SCORES_KEY))
            .thenAnswer((_) async => true);

        final bool result = await service.clearHighScores();

        expect(result, isTrue);
        verify(mockPrefs.remove(StorageService.HIGH_SCORES_KEY)).called(1);
      });

      test('returns false on clear failure', () async {
        when(mockPrefs.remove(StorageService.HIGH_SCORES_KEY))
            .thenAnswer((_) async => false);

        final bool result = await service.clearHighScores();

        expect(result, isFalse);
      });

      test('returns false on exception', () async {
        when(mockPrefs.remove(StorageService.HIGH_SCORES_KEY))
            .thenThrow(Exception('Storage error'));

        final bool result = await service.clearHighScores();

        expect(result, isFalse);
      });
    });

    group('saveThemeMode', () {
      test('saves light theme mode', () async {
        when(mockPrefs.setString(StorageService.THEME_MODE_KEY, 'light'))
            .thenAnswer((_) async => true);

        final bool result = await service.saveThemeMode('light');

        expect(result, isTrue);
        verify(mockPrefs.setString(StorageService.THEME_MODE_KEY, 'light'))
            .called(1);
      });

      test('saves dark theme mode', () async {
        when(mockPrefs.setString(StorageService.THEME_MODE_KEY, 'dark'))
            .thenAnswer((_) async => true);

        final bool result = await service.saveThemeMode('dark');

        expect(result, isTrue);
        verify(mockPrefs.setString(StorageService.THEME_MODE_KEY, 'dark'))
            .called(1);
      });

      test('saves system theme mode', () async {
        when(mockPrefs.setString(StorageService.THEME_MODE_KEY, 'system'))
            .thenAnswer((_) async => true);

        final bool result = await service.saveThemeMode('system');

        expect(result, isTrue);
        verify(mockPrefs.setString(StorageService.THEME_MODE_KEY, 'system'))
            .called(1);
      });

      test('returns false on save failure', () async {
        when(mockPrefs.setString(any, any)).thenAnswer((_) async => false);

        final bool result = await service.saveThemeMode('light');

        expect(result, isFalse);
      });

      test('returns false on exception', () async {
        when(mockPrefs.setString(any, any)).thenThrow(Exception('Storage error'));

        final bool result = await service.saveThemeMode('light');

        expect(result, isFalse);
      });
    });

    group('getThemeMode', () {
      test('returns system when no theme stored', () async {
        when(mockPrefs.getString(StorageService.THEME_MODE_KEY))
            .thenReturn(null);

        final String themeMode = await service.getThemeMode();

        expect(themeMode, equals('system'));
      });

      test('returns stored light theme', () async {
        when(mockPrefs.getString(StorageService.THEME_MODE_KEY))
            .thenReturn('light');

        final String themeMode = await service.getThemeMode();

        expect(themeMode, equals('light'));
      });

      test('returns stored dark theme', () async {
        when(mockPrefs.getString(StorageService.THEME_MODE_KEY))
            .thenReturn('dark');

        final String themeMode = await service.getThemeMode();

        expect(themeMode, equals('dark'));
      });

      test('returns system for invalid theme value', () async {
        when(mockPrefs.getString(StorageService.THEME_MODE_KEY))
            .thenReturn('invalid');

        final String themeMode = await service.getThemeMode();

        expect(themeMode, equals('system'));
      });

      test('returns system on exception', () async {
        when(mockPrefs.getString(StorageService.THEME_MODE_KEY))
            .thenThrow(Exception('Storage error'));

        final String themeMode = await service.getThemeMode();

        expect(themeMode, equals('system'));
      });
    });

    group('clearAll', () {
      test('clears all preferences successfully', () async {
        when(mockPrefs.clear()).thenAnswer((_) async => true);

        final bool result = await service.clearAll();

        expect(result, isTrue);
        verify(mockPrefs.clear()).called(1);
      });

      test('returns false on clear failure', () async {
        when(mockPrefs.clear()).thenAnswer((_) async => false);

        final bool result = await service.clearAll();

        expect(result, isFalse);
      });

      test('returns false on exception', () async {
        when(mockPrefs.clear()).thenThrow(Exception('Storage error'));

        final bool result = await service.clearAll();

        expect(result, isFalse);
      });
    });

    group('MAX_HIGH_SCORES constraint', () {
      test('keeps only top 10 scores', () async {
        // Create 12 scores
        final List<String> scoreStrings = [];
        for (int i = 1; i <= 12; i++) {
          scoreStrings.add(
            HighScore(score: i, timestamp: DateTime(2024, 1, i)).toJsonString(),
          );
        }
        when(mockPrefs.getStringList(StorageService.HIGH_SCORES_KEY))
            .thenReturn(scoreStrings);
        when(mockPrefs.setStringList(any, any)).thenAnswer((_) async => true);

        // Add another score
        await service.saveHighScore(50);

        // Verify setStringList was called with the key
        verify(mockPrefs.setStringList(
          StorageService.HIGH_SCORES_KEY,
          any,
        )).called(1);
      });
    });
  });
}
